spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/yourdatabase'
    username: 'yourusername'
    password: 'yourpassword'
    driver-class-name: org.postgresql.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 5001